# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='书名')),
                ('info', models.CharField(max_length=500, verbose_name='书简介')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('img', models.ImageField(blank=True, max_length=200, null=True, upload_to='book/img', verbose_name='封面')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('createtime', models.DateTimeField(db_index=True, default=(2018, 7, 19, 14, 37, 33, 3, 200, 0), verbose_name='添加时间')),
                ('cate', models.IntegerField(choices=[(0, '玄幻'), (1, '奇幻'), (2, '武侠'), (3, '仙侠'), (4, '都市'), (5, '现实'), (6, '军事'), (7, '历史'), (8, '游戏'), (9, '体育'), (10, '科幻'), (11, '灵异'), (12, '二次元'), (13, '短篇')])),
                ('price', models.IntegerField(default=0, verbose_name='单价')),
                ('count', models.IntegerField(default=0, verbose_name='阅读量')),
                ('state', models.IntegerField(choices=[(0, '连载'), (1, '完本')], default=0)),
                ('property', models.IntegerField(choices=[(0, '免费'), (1, 'VIP')], default=0)),
                ('size', models.IntegerField(choices=[(0, '30万字以下'), (1, '30-50万字'), (2, '50-100万字'), (3, '100-200万字'), (4, '200万字以上')])),
                ('quality', models.IntegerField(choices=[(0, '签约作品'), (1, '精品小说')])),
                ('refresh_data', models.IntegerField(choices=[(0, '三日内'), (1, '七日内'), (0, '半月内'), (1, '一月内')])),
            ],
        ),
    ]
